import './globals.css'
import type {Metadata} from 'next'
import {Rubik, Rubik_Dirt, Rubik_Maze} from 'next/font/google'
import Link from "next/link";
import {ReactNode} from "react";

const rubik = Rubik({weight: '500', subsets: ['latin-ext']})
const rubikDirt = Rubik_Dirt({weight: '400', subsets: ['latin-ext']})
const rubikMaze = Rubik_Maze({weight: '400', subsets: ['latin-ext']})

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({children}: { children: ReactNode }) {
    return (
        <html lang="en">
        <body className={`${rubik.className} flex flex-col lg:flex-row min-h-screen font-rubik bg-primary`}>
        <nav
            className="flex flex-col sticky top-0 z-10 basis-2/12 lg:basis-1/3 bg-primary text-white p-4 lg:h-screen lg:self-start">
            <div className="flex-1 flex flex-col justify-center">
                <h1 className={`${rubikDirt.className} text-5xl lg:text-8xl`}>Ore Adeleye</h1>
                <h2 className={`${rubikMaze.className} text-2xl lg:text-4xl`}>Full Stack Developer</h2>
            </div>
            <div className="flex flex-wrap space-x-3 self-end mt-8">
                <Link href="/">
                    <h3 className={`${rubikMaze.className} lg:text-xl`}>Portfolio</h3>
                </Link>
            </div>
        </nav>
        <div className="flex-1 flex flex-col bg-gray-200 text-gray-700">
            <div className="flex flex-col p-4 lg:justify-center lg:basis-3/4">
                {children}
            </div>
            <div className="flex-1 flex justify-between items-center p-4">
                <div>
                    <Link href="/" className="link-solid">
                        <span className="fa-solid fa-arrow-left"></span> Previous
                    </Link>
                </div>
                <Link href="/" className="link-solid">
                    Next <span className="fa-solid fa-arrow-right"></span>
                </Link>
            </div>
        </div>
        </body>
        </html>
    )
}
